title: Soham De
description: PhD student at University of Washington
previous: Microsft Research, Ashoka University
email: sohamde@uw.edu
twitter_username: actuallysoham
github_username: actuallysoham
linkedin_username: actuallysoham
bluesky_username: sohamde.in
scholar_username: i1ad6GmN4uoC

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  papers:
    output: true
    permalink: /papers/:path/ 